import test from "node:test";
import assert from "node:assert/strict";
import { generateCSS, resolveBrandDir, resolveBrandTree, cssVarNameForPath } from "./build-tokens.mjs";
import { join, dirname } from "node:path";
import { collectLeafPaths } from "./token-writes.mjs";

// Expected output: captured from the real generateCSS(resolveBrandDir())
// after the Task 4 token additions (§3.1) and the §0(a) alias fix — not
// hand-derived. Do not update this to match whatever the code produces —
// if this test fails, check the output against §3.1/§0(a)'s reasoning first.
const EXPECTED = `/* Design tokens — auto-generated by build-tokens.mjs. Do not edit directly. */

:root {
  --background: #faf9f5;
  --foreground: #141413;
  --color-accent: #ae97f7;
  --color-on-accent: #141413;
  --color-border: #e6dfd8;
  --color-surface: #ffffff;
  --color-playback-active: #141413;
  --color-loop-range: #ae97f7;
  --radius: 12px;
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-6: 24px;
  --space-8: 32px;
  --space-1_5: 6px;
  --sidebar-width: 240px;
  --state-hover-opacity: 8%;
  --state-focus-opacity: 10%;
  --state-pressed-opacity: 12%;
  --state-disabled-opacity: 50%;
  --state-muted-text-opacity: 40%;
  --state-muted-text-hover-opacity: 70%;
  --state-loop-range-opacity: 18%;
  --focus-ring-width: 2px;
  --focus-ring-offset: 2px;
  --focus-ring-color: #ae97f7;
  --component-color-field-swatch-size: 24px;
  --component-color-field-radius: 12px;
  --component-color-field-font-family: var(--font-geist-mono);
  --component-color-field-border: var(--color-border);
  --component-color-field-background: var(--color-surface);
  --component-color-field-text: var(--color-surface-text);
  --component-slider-track-color: var(--color-border);
  --component-segmented-control-gap: 24px;
  --component-segmented-control-border: var(--color-border);
  --component-button-padding-x: 12px;
  --component-button-padding-y: 6px;
  --component-button-radius: 12px;
  --component-button-font-family: var(--font-geist-sans);
  --component-button-primary-background: #ae97f7;
  --component-button-primary-text: #141413;
  --component-button-secondary-background: var(--color-surface);
  --component-button-secondary-text: var(--color-surface-text);
  --component-button-secondary-border: var(--color-border);
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
  --color-accent: var(--color-accent);
  --color-on-accent: var(--color-on-accent);
  --color-border: var(--color-border);
  --color-surface: var(--color-surface);
  --color-surface-text: var(--color-surface-text);
  --color-surface-hover: var(--color-surface-hover);
  --color-surface-active: var(--color-surface-active);
  --color-surface-active-text: var(--color-surface-active-text);
  --color-playback-active: var(--color-playback-active);
  --color-loop-range: var(--color-loop-range);
}

[data-theme="light"] {
  --background: #faf9f5;
  --foreground: #141413;
  --color-border: #e6dfd8;
  --color-surface: #ffffff;
  --color-surface-text: #141413;
  --color-surface-hover: #f0efe9;
  --color-surface-active: #141413;
  --color-surface-active-text: #faf9f5;
  --color-playback-active: #141413;
}

[data-theme="dark"] {
  --background: #1c1d1f;
  --foreground: #ededed;
  --color-border: #353434;
  --color-surface: #535353;
  --color-surface-text: #ffffff;
  --color-surface-hover: #5c5c5c;
  --color-surface-active: #ffffff;
  --color-surface-active-text: #212121;
  --color-playback-active: #ededed;
}
`;

test("generateCSS(default brand) matches the pinned §3 output character for character", () => {
  assert.equal(generateCSS(resolveBrandDir()), EXPECTED);
});

test("component.* leaves referencing theme-varying colors emit var() aliases, not literals", () => {
  const css = generateCSS(resolveBrandDir());
  // Theme-varying references stay live aliases so [data-theme] overrides flow through.
  assert.match(css, /--component-color-field-border: var\(--color-border\);/);
  assert.match(css, /--component-button-secondary-background: var\(--color-surface\);/);
  assert.match(css, /--component-button-secondary-text: var\(--color-surface-text\);/);
  // Theme-invariant references still resolve to literals as before.
  assert.match(css, /--component-button-primary-background: #ae97f7;/);
  assert.match(css, /--component-button-primary-text: #141413;/);
});

const childDir = () => join(dirname(resolveBrandDir()), "demo-child");

// Task 5a: parent-brand inheritance. demo-child (brands/demo-child/) declares
// { "parent": "default" } and overrides only semantic.color.accent -- proves
// both halves: the override cascades everywhere accent is referenced
// (--color-accent, --focus-ring-color, --component-button-primary-background),
// and everything NOT overridden (background/foreground/border/surface, the
// entire dark block, all other component.* leaves) resolves unchanged from
// the parent. Captured from the real generateCSS(demo-child dir) output, not
// hand-derived -- same discipline as EXPECTED above.
const DEMO_CHILD_EXPECTED = `/* Design tokens — auto-generated by build-tokens.mjs. Do not edit directly. */

:root {
  --background: #faf9f5;
  --foreground: #141413;
  --color-accent: #4a90d9;
  --color-on-accent: #141413;
  --color-border: #e6dfd8;
  --color-surface: #ffffff;
  --color-playback-active: #141413;
  --color-loop-range: #ae97f7;
  --radius: 12px;
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-6: 24px;
  --space-8: 32px;
  --space-1_5: 6px;
  --sidebar-width: 240px;
  --state-hover-opacity: 8%;
  --state-focus-opacity: 10%;
  --state-pressed-opacity: 12%;
  --state-disabled-opacity: 50%;
  --state-muted-text-opacity: 40%;
  --state-muted-text-hover-opacity: 70%;
  --state-loop-range-opacity: 18%;
  --focus-ring-width: 2px;
  --focus-ring-offset: 2px;
  --focus-ring-color: #4a90d9;
  --component-color-field-swatch-size: 24px;
  --component-color-field-radius: 12px;
  --component-color-field-font-family: var(--font-geist-mono);
  --component-color-field-border: var(--color-border);
  --component-color-field-background: var(--color-surface);
  --component-color-field-text: var(--color-surface-text);
  --component-slider-track-color: var(--color-border);
  --component-segmented-control-gap: 24px;
  --component-segmented-control-border: var(--color-border);
  --component-button-padding-x: 12px;
  --component-button-padding-y: 6px;
  --component-button-radius: 12px;
  --component-button-font-family: var(--font-geist-sans);
  --component-button-primary-background: #4a90d9;
  --component-button-primary-text: #141413;
  --component-button-secondary-background: var(--color-surface);
  --component-button-secondary-text: var(--color-surface-text);
  --component-button-secondary-border: var(--color-border);
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
  --color-accent: var(--color-accent);
  --color-on-accent: var(--color-on-accent);
  --color-border: var(--color-border);
  --color-surface: var(--color-surface);
  --color-surface-text: var(--color-surface-text);
  --color-surface-hover: var(--color-surface-hover);
  --color-surface-active: var(--color-surface-active);
  --color-surface-active-text: var(--color-surface-active-text);
  --color-playback-active: var(--color-playback-active);
  --color-loop-range: var(--color-loop-range);
}

[data-theme="light"] {
  --background: #faf9f5;
  --foreground: #141413;
  --color-border: #e6dfd8;
  --color-surface: #ffffff;
  --color-surface-text: #141413;
  --color-surface-hover: #f0efe9;
  --color-surface-active: #141413;
  --color-surface-active-text: #faf9f5;
  --color-playback-active: #141413;
}

[data-theme="dark"] {
  --background: #1c1d1f;
  --foreground: #ededed;
  --color-border: #353434;
  --color-surface: #535353;
  --color-surface-text: #ffffff;
  --color-surface-hover: #5c5c5c;
  --color-surface-active: #ffffff;
  --color-surface-active-text: #212121;
  --color-playback-active: #ededed;
}
`;

test("generateCSS(demo-child) inherits everything except its one override (accent)", () => {
  assert.equal(generateCSS(childDir()), DEMO_CHILD_EXPECTED);
});

test("resolveBrandTree(default brand) has no parent", () => {
  assert.deepEqual(resolveBrandTree(resolveBrandDir()).parentBrandDir, null);
});

test("resolveBrandTree(demo-child) merges parent's tree under its own override", () => {
  const { tree, parentBrandDir } = resolveBrandTree(childDir());
  assert.match(parentBrandDir, /brands[\\/]default$/);
  assert.equal(tree.semantic.color.accent.$value, "#4a90d9");
  assert.equal(tree.semantic.color.background.$value, "{primitive.color.paper}");
  assert.ok(tree.dark, "dark block inherited from parent");
});

test("cssVarNameForPath agrees with generateCSS's real output for every default-brand leaf (no drift between the two)", () => {
  const brandDir = resolveBrandDir();
  const css = generateCSS(brandDir);
  const { tree } = resolveBrandTree(brandDir);
  for (const { path } of collectLeafPaths(tree)) {
    const varName = cssVarNameForPath(path);
    if (varName === null) {
      assert.equal(path.split(".")[0], "primitive", `${path} unexpectedly has no CSS var name`);
      continue;
    }
    assert.ok(
      css.includes(`${varName}:`),
      `${path} -> "${varName}" not found as a declared property in generateCSS's real output`,
    );
  }
});
