import test from "node:test";
import assert from "node:assert/strict";
import { generateCSS, resolveBrandDir } from "./build-tokens.mjs";

// Expected output: the exact CSS pinned in the Task 2 spec (§3), frozen here.
// Do not update this to match whatever the code produces — if this test fails,
// check the output against §3's reasoning first (spec §9).
const EXPECTED = `/* Design tokens — auto-generated by build-tokens.mjs. Do not edit directly. */

:root {
  --background: #faf9f5;
  --foreground: #141413;
  --color-accent: #ae97f7;
  --color-on-accent: #141413;
  --color-border: #e6dfd8;
  --color-surface: #ffffff;
  --radius: 12px;
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-6: 24px;
  --space-8: 32px;
  --sidebar-width: 240px;
  --state-hover-opacity: 0.08;
  --state-focus-opacity: 0.1;
  --state-pressed-opacity: 0.12;
  --state-disabled-opacity: 0.5;
  --focus-ring-width: 2px;
  --focus-ring-offset: 2px;
  --focus-ring-color: #ae97f7;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
  --color-accent: var(--color-accent);
  --color-on-accent: var(--color-on-accent);
  --color-border: var(--color-border);
  --color-surface: var(--color-surface);
  --color-surface-text: var(--color-surface-text);
  --color-surface-hover: var(--color-surface-hover);
  --color-surface-active: var(--color-surface-active);
  --color-surface-active-text: var(--color-surface-active-text);
}

[data-theme="light"] {
  --background: #faf9f5;
  --foreground: #141413;
  --color-border: #e6dfd8;
  --color-surface: #ffffff;
  --color-surface-text: #141413;
  --color-surface-hover: #f0efe9;
  --color-surface-active: #141413;
  --color-surface-active-text: #faf9f5;
}

[data-theme="dark"] {
  --background: #1c1d1f;
  --foreground: #ededed;
  --color-border: #353434;
  --color-surface: #535353;
  --color-surface-text: #ffffff;
  --color-surface-hover: #5c5c5c;
  --color-surface-active: #ffffff;
  --color-surface-active-text: #212121;
}
`;

test("generateCSS(default brand) matches the pinned §3 output character for character", () => {
  assert.equal(generateCSS(resolveBrandDir()), EXPECTED);
});
